// <auto-generated />
using System;
using EcliptixPersistorMigrator.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcliptixPersistorMigrator.Migrations
{
    [DbContext(typeof(EcliptixSchemaContext))]
    [Migration("20250916143729_InitialEFSchema")]
    partial class InitialEFSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AppInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId")
                        .HasDatabaseName("IX_Devices_AppInstanceId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Devices_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Devices_DeviceId");

                    b.HasIndex("DeviceType")
                        .HasDatabaseName("IX_Devices_DeviceType")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Devices_UniqueId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.EventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_EventLogs_EventType")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_EventLogs_OccurredAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_EventLogs_SessionId")
                        .HasFilter("IsDeleted = 0 AND SessionId IS NOT NULL");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_EventLogs_Severity")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventLogs_UniqueId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_EventLogs_UserId")
                        .HasFilter("IsDeleted = 0 AND UserId IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_EventLogs_Entity")
                        .HasFilter("IsDeleted = 0 AND EntityType IS NOT NULL AND EntityId IS NOT NULL");

                    b.ToTable("EventLogs", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.FailedOtpAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AttemptedValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("OtpRecordId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FailedOtpAttempts_AttemptedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_FailedOtpAttempts_IpAddress")
                        .HasFilter("IsDeleted = 0 AND IpAddress IS NOT NULL");

                    b.HasIndex("OtpRecordId")
                        .HasDatabaseName("IX_FailedOtpAttempts_OtpRecordId");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FailedOtpAttempts_UniqueId");

                    b.ToTable("FailedOtpAttempts", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.LoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SuccessfulAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_LoginAttempts_AttemptedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_LoginAttempts_IpAddress")
                        .HasFilter("IsDeleted = 0 AND IpAddress IS NOT NULL");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_LoginAttempts_MembershipId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_LoginAttempts_SessionId")
                        .HasFilter("IsDeleted = 0 AND SessionId IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LoginAttempts_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_LoginAttempts_UniqueId");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.Membership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AppDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreationStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PhoneNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("SecureKey")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("inactive");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("VerificationFlowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppDeviceId")
                        .HasDatabaseName("IX_Memberships_AppDeviceId");

                    b.HasIndex("PhoneNumberId")
                        .HasDatabaseName("IX_Memberships_PhoneNumberId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Memberships_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Memberships_UniqueId");

                    b.HasIndex("VerificationFlowId");

                    b.HasIndex("PhoneNumberId", "AppDeviceId", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("UQ_Memberships_ActiveMembership");

                    b.ToTable("Memberships", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Memberships_CreationStatus", "CreationStatus IN ('otp_verified', 'secure_key_set', 'passphrase_set')");

                            t.HasCheckConstraint("CHK_Memberships_Status", "Status IN ('active', 'inactive')");
                        });
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.MembershipAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttemptType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MembershipAttempts_AttemptedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("IX_MembershipAttempts_IpAddress")
                        .HasFilter("IsDeleted = 0 AND IpAddress IS NOT NULL");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_MembershipAttempts_MembershipId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MembershipAttempts_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MembershipAttempts_UniqueId");

                    b.ToTable("MembershipAttempts", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.MobileDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PhoneNumberId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelationshipType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("primary");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_MobileDevices_DeviceId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MobileDevices_IsActive")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("LastUsedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileDevices_LastUsedAt")
                        .HasFilter("IsDeleted = 0 AND LastUsedAt IS NOT NULL");

                    b.HasIndex("PhoneNumberId")
                        .HasDatabaseName("IX_MobileDevices_PhoneNumberId");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileDevices_UniqueId");

                    b.HasIndex("PhoneNumberId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileDevices_PhoneDevice");

                    b.ToTable("MobileDevices", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.MobileNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Region")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileNumbers_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_MobileNumbers_Region")
                        .HasFilter("IsDeleted = 0 AND Region IS NOT NULL");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileNumbers_UniqueId");

                    b.HasIndex("PhoneNumber", "Region")
                        .HasDatabaseName("IX_MobileNumbers_PhoneNumber_Region")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("PhoneNumber", "Region", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileNumbers_ActiveNumberRegion")
                        .HasFilter("[Region] IS NOT NULL");

                    b.ToTable("MobileNumbers", (string)null);
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OtpValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VerificationFlowId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_OtpCodes_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_OtpCodes_ExpiresAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OtpCodes_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_OtpCodes_UniqueId");

                    b.HasIndex("VerificationFlowId")
                        .HasDatabaseName("IX_OtpCodes_VerificationFlowId");

                    b.ToTable("OtpCodes", null, t =>
                        {
                            t.HasCheckConstraint("CHK_OtpCodes_Status", "Status IN ('active', 'used', 'expired', 'invalid')");
                        });
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.VerificationFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AppDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ConnectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<short>("OtpCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<long>("PhoneNumberId")
                        .HasColumnType("bigint");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("unspecified");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AppDeviceId")
                        .HasDatabaseName("IX_VerificationFlows_AppDeviceId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_VerificationFlows_ExpiresAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("PhoneNumberId")
                        .HasDatabaseName("IX_VerificationFlows_PhoneNumberId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VerificationFlows_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_VerificationFlows_UniqueId");

                    b.ToTable("VerificationFlows", null, t =>
                        {
                            t.HasCheckConstraint("CHK_VerificationFlows_Purpose", "Purpose IN ('unspecified', 'registration', 'login', 'password_recovery', 'update_phone')");

                            t.HasCheckConstraint("CHK_VerificationFlows_Status", "Status IN ('pending', 'verified', 'expired', 'failed')");
                        });
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.FailedOtpAttempt", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.OtpCode", "OtpRecord")
                        .WithMany("FailedAttempts")
                        .HasForeignKey("OtpRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FailedOtpAttempts_OtpCodes");

                    b.Navigation("OtpRecord");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.LoginAttempt", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.Membership", "Membership")
                        .WithMany("LoginAttempts")
                        .HasForeignKey("MembershipId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoginAttempts_Memberships");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.Membership", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.Device", "AppDevice")
                        .WithMany("Memberships")
                        .HasForeignKey("AppDeviceId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_Devices");

                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.MobileNumber", "PhoneNumber")
                        .WithMany("Memberships")
                        .HasForeignKey("PhoneNumberId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_MobileNumbers");

                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.VerificationFlow", "VerificationFlow")
                        .WithMany("Memberships")
                        .HasForeignKey("VerificationFlowId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_VerificationFlows");

                    b.Navigation("AppDevice");

                    b.Navigation("PhoneNumber");

                    b.Navigation("VerificationFlow");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.MembershipAttempt", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.Membership", "Membership")
                        .WithMany("MembershipAttempts")
                        .HasForeignKey("MembershipId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MembershipAttempts_Memberships");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.MobileDevice", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.Device", "Device")
                        .WithMany("MobileDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MobileDevices_Devices");

                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.MobileNumber", "PhoneNumber")
                        .WithMany("MobileDevices")
                        .HasForeignKey("PhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MobileDevices_MobileNumbers");

                    b.Navigation("Device");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.OtpCode", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.VerificationFlow", "VerificationFlow")
                        .WithMany("OtpCodes")
                        .HasForeignKey("VerificationFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OtpCodes_VerificationFlows");

                    b.Navigation("VerificationFlow");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.VerificationFlow", b =>
                {
                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.Device", "AppDevice")
                        .WithMany("VerificationFlows")
                        .HasForeignKey("AppDeviceId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VerificationFlows_Devices");

                    b.HasOne("EcliptixPersistorMigrator.Schema.Entities.MobileNumber", "PhoneNumber")
                        .WithMany("VerificationFlows")
                        .HasForeignKey("PhoneNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VerificationFlows_MobileNumbers");

                    b.Navigation("AppDevice");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.Device", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MobileDevices");

                    b.Navigation("VerificationFlows");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.Membership", b =>
                {
                    b.Navigation("LoginAttempts");

                    b.Navigation("MembershipAttempts");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.MobileNumber", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MobileDevices");

                    b.Navigation("VerificationFlows");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.OtpCode", b =>
                {
                    b.Navigation("FailedAttempts");
                });

            modelBuilder.Entity("EcliptixPersistorMigrator.Schema.Entities.VerificationFlow", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("OtpCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
