// <auto-generated />
using System;
using Ecliptix.Memberships.Persistor.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecliptix.Memberships.Persistor.Migrations
{
    [DbContext(typeof(EcliptixSchemaContext))]
    [Migration("20251002123248_UpdateStoredProcs_AddMaskingKey")]
    partial class UpdateStoredProcs_AddMaskingKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AppInstanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId")
                        .HasDatabaseName("IX_Devices_AppInstanceId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Device_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Devices_DeviceId");

                    b.HasIndex("DeviceType")
                        .HasDatabaseName("IX_Devices_DeviceType")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Device_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Device_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.EventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_EventLog_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_EventLogs_EventType")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("IX_EventLogs_OccurredAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_EventLogs_SessionId")
                        .HasFilter("IsDeleted = 0 AND SessionId IS NOT NULL");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_EventLogs_Severity")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventLog_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_EventLog_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_EventLogs_UserId")
                        .HasFilter("IsDeleted = 0 AND UserId IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_EventLogs_Entity")
                        .HasFilter("IsDeleted = 0 AND EntityType IS NOT NULL AND EntityId IS NOT NULL");

                    b.ToTable("EventLogs", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.FailedOtpAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AttemptedValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("OtpRecordId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FailedOtpAttempts_AttemptedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FailedOtpAttempt_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("OtpRecordId")
                        .HasDatabaseName("IX_FailedOtpAttempts_OtpRecordId");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_FailedOtpAttempt_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FailedOtpAttempt_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("FailedOtpAttempts", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.LoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MembershipUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SuccessfulAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_LoginAttempts_AttemptedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_LoginAttempt_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("IsSuccess")
                        .HasDatabaseName("IX_LoginAttempts_IsSuccess")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MembershipUniqueId")
                        .HasDatabaseName("IX_LoginAttempts_MembershipUniqueId");

                    b.HasIndex("MobileNumber")
                        .HasDatabaseName("IX_LoginAttempts_MobileNumber")
                        .HasFilter("IsDeleted = 0 AND MobileNumber IS NOT NULL");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("IX_LoginAttempts_Outcome")
                        .HasFilter("IsDeleted = 0 AND Outcome IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_LoginAttempts_SessionId")
                        .HasFilter("IsDeleted = 0 AND SessionId IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LoginAttempts_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LoginAttempts_Timestamp")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_LoginAttempt_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_LoginAttempt_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("LoginAttempts", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MasterKeyShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("EncryptedShare")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MembershipUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShareIndex")
                        .HasColumnType("int");

                    b.Property<string>("ShareMetadata")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MasterKeyShare_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MembershipUniqueId");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MasterKeyShare_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MasterKeyShare_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("MasterKeyShares", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.Membership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AppDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreationStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("Mac")
                        .HasColumnType("VARBINARY(64)");

                    b.Property<byte[]>("MaskingKey")
                        .HasColumnType("VARBINARY(32)")
                        .HasColumnName("MAC (UUID)");

                    b.Property<Guid>("MobileNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("SecureKey")
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("inactive");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("VerificationFlowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppDeviceId")
                        .HasDatabaseName("IX_Memberships_AppDeviceId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Membership_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MobileNumberId")
                        .HasDatabaseName("IX_Memberships_MobileNumberId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Memberships_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Memberships_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_Membership_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("VerificationFlowId");

                    b.HasIndex("MobileNumberId", "AppDeviceId", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("UQ_Memberships_ActiveMembership");

                    b.ToTable("Memberships", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Memberships_CreationStatus", "CreationStatus IN ('otp_verified', 'secure_key_set', 'passphrase_set')");

                            t.HasCheckConstraint("CHK_Memberships_Status", "Status IN ('active', 'inactive')");
                        });
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MembershipAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttemptType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MembershipAttempts_AttemptedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MembershipAttempt_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_MembershipAttempts_MembershipId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MembershipAttempts_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MembershipAttempt_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MembershipAttempt_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("MembershipAttempts", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MobileDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MobileNumberId")
                        .HasColumnType("bigint");

                    b.Property<string>("RelationshipType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("primary");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileDevice_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("IX_MobileDevices_DeviceId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MobileDevices_IsActive")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("LastUsedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileDevices_LastUsedAt")
                        .HasFilter("IsDeleted = 0 AND LastUsedAt IS NOT NULL");

                    b.HasIndex("MobileNumberId")
                        .HasDatabaseName("IX_MobileDevices_MobileNumberId");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileDevice_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileDevice_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MobileNumberId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileDevices_PhoneDevice");

                    b.ToTable("MobileDevices", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MobileNumber", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Region")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileNumbers_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_MobileNumbers_Region")
                        .HasFilter("IsDeleted = 0 AND Region IS NOT NULL");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileNumber_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_MobileNumber_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Number", "Region")
                        .HasDatabaseName("IX_MobileNumbers_MobileNumber_Region")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Number", "Region", "IsDeleted")
                        .IsUnique()
                        .HasDatabaseName("UQ_MobileNumbers_ActiveNumberRegion")
                        .HasFilter("[Region] IS NOT NULL");

                    b.ToTable("MobileNumbers", (string)null);
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.OtpCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OtpSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("active");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("VerificationFlowId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_OtpCode_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_OtpCodes_ExpiresAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OtpCodes_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_OtpCode_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_OtpCode_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("VerificationFlowId")
                        .HasDatabaseName("IX_OtpCodes_VerificationFlowId");

                    b.ToTable("OtpCodes", null, t =>
                        {
                            t.HasCheckConstraint("CHK_OtpCodes_Status", "Status IN ('active', 'used', 'expired', 'invalid')");
                        });
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.VerificationFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AppDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("ConnectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("MobileNumberId")
                        .HasColumnType("bigint");

                    b.Property<short>("OtpCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("unspecified");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<Guid>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AppDeviceId")
                        .HasDatabaseName("IX_VerificationFlows_AppDeviceId");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_VerificationFlow_CreatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_VerificationFlows_ExpiresAt")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("MobileNumberId")
                        .HasDatabaseName("IX_VerificationFlows_MobileNumberId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VerificationFlows_Status")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UniqueId")
                        .IsUnique()
                        .HasDatabaseName("UQ_VerificationFlow_UniqueId");

                    b.HasIndex("UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_VerificationFlow_UpdatedAt")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("VerificationFlows", null, t =>
                        {
                            t.HasCheckConstraint("CHK_VerificationFlows_Purpose", "Purpose IN ('unspecified', 'registration', 'login', 'password_recovery', 'update_phone')");

                            t.HasCheckConstraint("CHK_VerificationFlows_Status", "Status IN ('pending', 'verified', 'expired', 'failed')");
                        });
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.FailedOtpAttempt", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.OtpCode", "OtpRecord")
                        .WithMany("FailedAttempts")
                        .HasForeignKey("OtpRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FailedOtpAttempts_OtpCodes");

                    b.Navigation("OtpRecord");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.LoginAttempt", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.Membership", "Membership")
                        .WithMany("LoginAttempts")
                        .HasForeignKey("MembershipUniqueId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoginAttempts_Memberships");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MasterKeyShare", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.Membership", "Membership")
                        .WithMany("MasterKeyShares")
                        .HasForeignKey("MembershipUniqueId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_MasterKeyShares_Memberships");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.Membership", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.Device", "AppDevice")
                        .WithMany("Memberships")
                        .HasForeignKey("AppDeviceId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_Devices");

                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.MobileNumber", "MobileNumber")
                        .WithMany("Memberships")
                        .HasForeignKey("MobileNumberId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_MobileNumbers");

                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.VerificationFlow", "VerificationFlow")
                        .WithMany("Memberships")
                        .HasForeignKey("VerificationFlowId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Memberships_VerificationFlows");

                    b.Navigation("AppDevice");

                    b.Navigation("MobileNumber");

                    b.Navigation("VerificationFlow");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MembershipAttempt", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.Membership", "Membership")
                        .WithMany("MembershipAttempts")
                        .HasForeignKey("MembershipId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MembershipAttempts_Memberships");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MobileDevice", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.Device", "Device")
                        .WithMany("MobileDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MobileDevices_Devices");

                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.MobileNumber", "MobileNumber")
                        .WithMany("MobileDevices")
                        .HasForeignKey("MobileNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MobileDevices_MobileNumbers");

                    b.Navigation("Device");

                    b.Navigation("MobileNumber");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.OtpCode", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.VerificationFlow", "VerificationFlow")
                        .WithMany("OtpCodes")
                        .HasForeignKey("VerificationFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OtpCodes_VerificationFlows");

                    b.Navigation("VerificationFlow");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.VerificationFlow", b =>
                {
                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.Device", "AppDevice")
                        .WithMany("VerificationFlows")
                        .HasForeignKey("AppDeviceId")
                        .HasPrincipalKey("UniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VerificationFlows_Devices");

                    b.HasOne("Ecliptix.Memberships.Persistor.Schema.Entities.MobileNumber", "MobileNumber")
                        .WithMany("VerificationFlows")
                        .HasForeignKey("MobileNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VerificationFlows_MobileNumbers");

                    b.Navigation("AppDevice");

                    b.Navigation("MobileNumber");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.Device", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MobileDevices");

                    b.Navigation("VerificationFlows");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.Membership", b =>
                {
                    b.Navigation("LoginAttempts");

                    b.Navigation("MasterKeyShares");

                    b.Navigation("MembershipAttempts");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.MobileNumber", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MobileDevices");

                    b.Navigation("VerificationFlows");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.OtpCode", b =>
                {
                    b.Navigation("FailedAttempts");
                });

            modelBuilder.Entity("Ecliptix.Memberships.Persistor.Schema.Entities.VerificationFlow", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("OtpCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
