namespace Ecliptix.Memberships.Persistor.StoredProcedures.Models.Enums;

public enum ProcedureOutcome
{
    Created,
    Success,
    SecureKeySet,
    SecureKeyUpdated,
    Updated,
    Verified,
    Found,

    AlreadyExists,
    ActiveFlowExists,
    DeviceNotFound,
    DeviceRateLimitExceeded,
    Error,
    EligibleForRecovery,
    Failed,
    FlowExpired,
    FlowNotFound,
    FlowNotFoundOrInvalid,
    UpdateFailed,
    Invalid,
    InvalidCode,
    InvalidSecureKey,
    InvalidTransition,
    InactiveMembership,
    MembershipBlocked,
    MembershipNotFound,
    MaxAttemptsExceeded,
    MobileNumberNotFound,
    MaxOtpAttemptsReached,
    MembershipAlreadyExists,
    MobileNumberCannotBeEmpty,
    NoData,
    NotFound,
    NoActiveOtp,
    NoSecureKey,
    NoPendingOtp,
    OtpLimitExceeded,
    ResendAllowed,
    RateLimitExceeded,
    ResendCooldownActive,
    VerificationFlowNotFound,
    SqlError,
    SecureKeyNotSet
}